# Generated by Django 3.1.5 on 2021-01-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210123_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='Learning', max_length=50),
            preserve_default=False,
        ),
    ]
