# Generated by Django 3.1.5 on 2021-01-23 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210123_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='status',
            new_name='about_me',
        ),
    ]
