# Generated by Django 3.1.5 on 2021-01-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210123_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.CharField(default='', max_length=50),
        ),
    ]
