# Generated by Django 3.1.5 on 2021-01-25 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210123_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='about_me',
            new_name='short_bio',
        ),
    ]
