# Generated by Django 3.1.5 on 2021-02-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Anonymous', max_length=100, null=True)),
                ('issue', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
