# Generated by Django 3.1.5 on 2021-03-14 14:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20210213_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
