# Generated by Django 3.1.5 on 2021-02-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210203_0711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_activity',
            old_name='post_id',
            new_name='post',
        ),
    ]
