# Generated by Django 3.1.5 on 2021-02-03 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210203_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote_table',
            name='time_posted',
        ),
    ]
