# Generated by Django 3.1.5 on 2021-02-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210204_0632'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment_table',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='comment_table',
            constraint=models.UniqueConstraint(fields=('post', 'author'), name='pk_comment'),
        ),
    ]
