# Generated by Django 3.1.5 on 2021-02-04 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210204_0633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment_table',
            options={'ordering': ['time_posted']},
        ),
    ]
