# Generated by Django 3.1.5 on 2021-02-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210205_0020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-time_posted']},
        ),
    ]
