# Generated by Django 3.1.5 on 2021-02-12 15:35

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20210212_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=False, null=True, quality=75, size=[630, 500], upload_to='post_images'),
        ),
    ]
