# Generated by Django 3.1.5 on 2021-02-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20210212_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('Machine Learning', 'ML'), ('Artificial Intelligence', 'AI'), ('Art', 'ART'), ('Astrology', 'ASTROLOGY'), ('Photo', 'PHOTO'), ('Programming', 'PROGRAMMING'), ('Miscallenous', 'MISC')], default='MISC', max_length=23),
        ),
    ]
