# Generated by Django 3.1.5 on 2021-02-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('MACHINE LEARNING', 'Machine Learning'), ('ARTIFICIAL INTELLIGENCE', 'Artificial Intelligence'), ('ART', 'Art'), ('ASTROLOGY', 'Astrology'), ('PHOTO', 'Photo'), ('PROGRAMMING', 'Programming'), ('MISCALLENOUS', 'Miscallenous')], default='MISC', max_length=23),
        ),
    ]
